# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Source global definitions
if [ -f ./.git_shell.sh ]; then
	. ./.git_shell.sh
fi

# User specific aliases and functions

alias ll='ls -l'
alias la='ls -la'
alias rm='rm -v'
alias tar='tar -v'
alias vi='vim'
alias grails='grails -verbose'
