#/bin/bash

export PATH=$HOME/.bin:$PATH
export TERM='xterm-256color'

# Common aliases

alias ll='ls -l '
alias la='ls -la '
alias rm='rm -v '
alias cp='cp -v '

# Git aliases

alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit '
alias gd='git diff '
alias go='git checkout '
alias gp='git push '
alias gu='git pull '
alias gf='git fetch '
alias gm='git merge '
alias gmt='git mergetool '
alias gl='git log '
alias gll='git log --oneline '

# Brew aliases

alias bi='brew install '
alias bf='brew info '
alias bl='brew list -l '
alias bs='brew search '
alias bh='brew home '
alias bd='brew update '
alias bu='brew uninstall '
alias bg='brew upgrade '
alias bci='brew cask install '
alias bcf='brew cask info '
alias bcl='brew cask list '
alias bcs='brew cask search '
alias bch='brew cask home '
alias bcu='brew cask uninstall '
alias bcz='brew cask zap '

# Perforce aliases

alias p4w='p4 workspace '
alias p4a='p4 add '
alias p4e='p4 edit '
alias p4d='p4 delete '
alias p4c='p4 change '
alias p4dc='p4 describe '
