export PATH=$HOME/.bin:$PATH

alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit'
alias gca='git commit -a'
alias gd='git diff'
alias go='git checkout '
alias gp='git push'
alias gpom='git push origin master'
