" ==================================
" ===          Plugins           ===
" ==================================

set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" This is a VIM plugin package manager
Plugin 'VundleVim/Vundle.vim'

" File browser tree. Like Navigator in Eclipse.
Plugin 'scrooloose/nerdtree'

" A pack of color schemes
Plugin 'daviddavis/vim-colorpack'

" Easily comment lines
Plugin 'scrooloose/nerdcommenter'

" Close a sinlge buffer without closing the window
Plugin 'Soares/butane.vim'

" Fancy status bar
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" Tabularize the selected text using '=' as a separator
Plugin 'godlygeek/tabular'

" Adds external support for linters.
Plugin 'scrooloose/syntastic'

" Adds some additional utilities and functionality for developing VIM
Plugin 'L9'

" Adds tab view that is showing the methods and fields of the opened class. The same as Outline in Eclipse.
Plugin 'majutsushi/tagbar'

" Support for ActionScript
Plugin 'actionscript'

" Integration with Grep and VimGrep
Plugin 'vim-scripts/EasyGrep'

" Support for JavaScript
Plugin 'pangloss/vim-javascript'

" Highlight some JavaScript libraries
Plugin 'othree/javascript-libraries-syntax.vim'

" Fuzzy file/buffer finder
Plugin 'ctrlpvim/ctrlp.vim'

" A bunch of snippets (engine)
if v:version > 740
    Plugin 'SirVer/ultisnips'
else
    Plugin 'MarcWeber/vim-addon-mw-utils'
    Plugin 'tomtom/tlib_vim'
    Plugin 'garbas/vim-snipmate'
endif

" Snippets are separated from the engine. Add this if you want them:
Plugin 'honza/vim-snippets'

" HTML5 support
Plugin 'othree/html5-syntax.vim'
Plugin 'othree/html5.vim'

" LESS support
Plugin 'groenewege/vim-less'

" Highlight the matching tag
Plugin 'gregsexton/MatchTag'

" UNIX file modification operations
Plugin 'tpope/vim-eunuch'

" Support for typescript
Plugin 'leafgarland/typescript-vim'

" Update the CSS completion with latest standards
Plugin 'othree/csscomplete.vim'

" Manage marks
Plugin 'kshenoy/vim-signature'

" Surround actions
Plugin 'tpope/vim-surround'

" Expand abreviations
Plugin 'mattn/emmet-vim'

" Git support - adds sign infront of the file line indication if the text was
" added/remove/edited
Plugin 'airblade/vim-gitgutter'

" Add Git support in NERDTree
" May be slow sometimes
Plugin 'Xuyuanp/nerdtree-git-plugin'

" Support for GUI color schemes in the non-gui environments
Plugin 'godlygeek/csapprox'

" Enchances the VIM search
Plugin 'henrik/vim-indexed-search'

" Shows the VIM's undo tree (history)
Plugin 'mbbill/undotree'

" Allows method parameters, array elements, etc. to be moved left or right
Plugin 'AndrewRadev/sideways.vim'

if v:version > 750
    " Awsome library for autocompletion
    Plugin 'Valloric/YouCompleteMe'
else
    Plugin 'davidhalter/jedi-vim'
    Plugin 'ternjs/tern_for_vim'
endif

" Angular stuff
Plugin 'burnettk/vim-angular'

" Highlith XML/HTML opening or closing tag
Plugin 'jiangmiao/auto-pairs'

" Perforce integration plugin
Plugin 'nfvs/vim-perforce'

call vundle#end()
filetype plugin indent on

" ==================================
" ===     Configure behavior     ===
" ==================================

syntax on

set autoindent
set copyindent
set smartindent
set backup
set writebackup
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set incsearch
set hlsearch
set cursorline
set number
set encoding=utf8
set wildchar=<Tab>
set wildmenu
set wildmode=list:full
set ignorecase
set smartcase
set smarttab
set ff=unix
set scrolloff=4
set noshowcmd
set hidden
set ruler
set laststatus=2
set undofile
set modelines=0
set title
set dir=~/.vim/sessions//
set backupdir=~/.vim/backup//
set undodir=~/.vim/undo//
set wrap
set showmatch
set history=1000     " remember more commands and search history
set undolevels=1000  " use many muchos levels of undo
set noerrorbells     " Don't blink on error
set visualbell t_vb= " Don't beep on error
set relativenumber
set foldcolumn=1     " show an additional column for fold indicator

inoremap <C-]> <ESC> " leave insert mode using both square brakets

" Load and Save the configuration file
nnoremap <silent> <Leader>lv :e $MYVIMRC<CR>
nnoremap <silent> <Leader>sv :so $MYVIMRC<CR>

" Toggle folded text
nnoremap <silent> <S-space> za

" Toggle folded text and clear search result highlight
nnoremap <silent> <space> :noh<CR>

" Delete white spaces on file save
autocmd BufWritePre * :%s/\s\+$//ge

" Easier moving to start/end line
nnoremap <leader>a ^
nnoremap <leader>e $
vnoremap <leader>a ^
vnoremap <leader>e $<Left>

" New line
inoremap <S-Enter> <Esc>o
inoremap <C-Enter> <Esc>O

" ==================================
" ===     Configure VIM JS       ===
" ==================================

let g:javascript_enable_domhtmlcss=1
let g:javascript_enable_domhtmlcss = 1
let g:javascript_ignore_javaScriptdoc = 1
let g:javascript_plugin_jsdoc = 1
let g:javascript_plugin_ngdoc = 1

autocmd BufEnter *.js set tw=79 sw=3 ts=3 sta et fo=croql
autocmd BufEnter *.ts set tw=79 sw=3 ts=3 sta et fo=croql

let g:used_javascript_libs = 'angularjs,jquery,requirejs'

" ==================================
" ===   Configure ultisnip       ===
" ==================================

let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-j>"
let g:UltiSnipsJumpBackwardTrigger="<c-k>"

" ==================================
" ===             XML            ===
" ==================================

autocmd BufEnter *.xml set tw=79 sw=3 ts=3 sta et fo=croql
autocmd BufEnter *.html set tw=79 sw=3 ts=3 sta et fo=croql

" ==================================
" ===     Configure Python       ===
" ==================================

autocmd FileType python setlocal completeopt-=preview
autocmd BufEnter *.py set tw=79 sw=3 ts=3 sta et fo=croql
autocmd BufEnter *.sc set tw=79 sw=3 ts=3 sta et fo=croql
autocmd BufEnter *.sc setlocal filetype=python

" ==================================
" ===     Configure Tern JS      ===
" ==================================

nnoremap <Leader>dd :TernDef<CR>
nnoremap <Leader>dp :TernDefPreview<CR>
nnoremap <Leader>ds :TernDefSplit<CR>
nnoremap <Leader>dt :TernDefTab<CR>
nnoremap <Leader>kk :TernDoc<CR>
nnoremap <Leader>kb :TernDocBrowse<CR>
nnoremap <Leader>n :TernRefs<CR>
nnoremap <Leader>r :TernRename<CR>

" ==================================
" ===      Configure CSS         ===
" ==================================

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS noci
autocmd BufNewFile,BufRead *.less set filetype=less
autocmd FileType less set omnifunc=csscomplete#CompleteCSS
autocmd BufEnter *.css set tw=79 sw=3 ts=3 sta et fo=croql
autocmd BufEnter *.scss set tw=79 sw=3 ts=3 sta et fo=croql

" ==================================
" ===     Configure Syntastic    ===
" ==================================

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0
let g:syntastic_mode_map={ "mode": "passive" }
let g:sytastic_enable_highlighting=1
let g:syntastic_javascript_checkers = ['jshint']
nnoremap <leader>ll :SyntasticCheck<CR>
nnoremap <leader>ln :lnext<CR>
nnoremap <leader>lp :lprevious<CR>
nnoremap <leader>lr :SyntasticReset<CR>

" ==================================
" =  Configure AirLine status bar  =
" ==================================

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline_theme='wombat'

" ==================================
" ===      Set color scheme      ===
" ==================================

set background=dark
colo jellybeans

" ==================================
" ===     Configure NERD tree    ===
" ==================================

nnoremap <silent> <Leader>0 :NERDTreeToggle<CR>
" Close VIM if the only window left is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" ==================================
" ===       Configure TagBar     ===
" ==================================

nnoremap <silent> <Leader>9 :TagbarToggle<CR>

" ==================================
" ======    Configure Butane   =====
" ==================================

nnoremap <leader>q :Bclose<CR>

" ==================================
" ===    Configure CtrlP find    ===
" ==================================

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 0

nnoremap <C-e> :CtrlPBuffer<CR>

" ==================================
" = Configure clipboard management =
" ==================================

" Copy to clipboard
noremap <Leader>y "+y

" Paste from clipboard
noremap <Leader>p "+p
noremap <Leader>P "+P

vnoremap <Leader>p "+p
vnoremap <Leader>P "+P

inoremap <Leader>p <C-r>+
inoremap <Leader>P <C-r>+

" ==================================
" ===          Undotree          ===
" ==================================

nnoremap <Leader>5 :UndotreeToggle<cr>

" ==================================
" ===     Configure behavior     ===
" ==================================

nnoremap <Leader>sl :SidewaysLeft<CR>
nnoremap <Leader>sr :SidewaysRight<CR>

" ==================================
" ===       Make grep faster     ===
" ==================================

" The Silver Searcher
if executable('ag')
  " Use ag over grep
  set grepprg=ag\ --nogroup\ --nocolor

  " Use ag in CtrlP for listing files. Lightning fast and respects .gitignore
  let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'

  " bind K to grep word under cursor
  nnoremap KK :grep "\b<C-R><C-W>\b"<CR>:cw<CR>
endif

" ==================================
" ===      Window navigation     ===
" ==================================

" Easy navigation between panes
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Scrolling in Insert mode
inoremap <C-E> <C-X><C-E>
inoremap <C-Y> <C-X><C-Y>

" Command mode navigation

" start of line
cnoremap <C-a> <Home>
" end of line
cnoremap <C-e> <End>
" back one character
cnoremap <C-h> <Left>
" forward one character
cnoremap <C-l> <Right>
" delete character under cursor
cnoremap <C-d> <Del>
" recall newer command-line
cnoremap <C-n> <Down>
" recall previous (older) command-line
cnoremap <C-p> <Up>

" Move display lines instead of real lines
nnoremap k  gk
nnoremap gk k
nnoremap j  gj
nnoremap gj j

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" Run ctags
nnoremap <silent> <leader>rc :!ctags -R .<CR>

" Toggle the paste option
set pastetoggle=<f5>

nnoremap <leader>ts :tselect <C-r><C-w><CR>

nnoremap ; :
